name: GitHub Actions Demo
on: 
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: composer install
      - run:  composer require
      - run: composer exec phpunit MathTest.php
 

