name: Github Actions Demo
 
# Triggers the workflow on push or pull request events
on: [push, pull_request]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '7.3'
            tools: phpstan, composer
 
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
        
 
      - name: "Run tests"
       
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml
 
 

